My_Third_Project/Login_app/urls.py
from django.conf.urls import url
from django.urls import path
from Login_app import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

app_name = 'Login_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Third_Project/My_Third_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Login_app.urls')),
    path('admin/', admin.site.urls),
]

My_Third_Project/Login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    facebook_id = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

My_Third_Project/Login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from Login_app.models import UserInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password', 'email')

class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields =('facebook_id', 'profile_pic')

My_Third_Project/Login_app/views.py
from django.shortcuts import render
from Login_app.forms import UserForm, UserInfoForm
from Login_app.models import UserInfo
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.
def login_page(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('Login_app:index'))
    else:
        return render(request, 'Login_app/login.html', context={})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Login_app:index'))
            else:
                return HttpResponse("Account is not active!!")

        else:
            return HttpResponse("Login Details are Wrong!")

    else:
        return HttpResponseRedirect(reverse('Login_app:login'))
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:login'))

def index(request):
    diction={}
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = UserInfo.objects.get(user__pk=user_id)
        diction={'user_basic_info': user_basic_info, 'user_more_info': user_more_info}
    return render(request, 'Login_app/index.html', context=diction)

def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('Login_app:index'))
    else:
        registered = False
        if request.method == 'POST':
            user_form = UserForm(data=request.POST)
            user_info_form = UserInfoForm(data=request.POST)

            if user_form.is_valid() and user_info_form.is_valid():
                user = user_form.save()
                user.set_password(user.password)
                user.save()

                user_info = user_info_form.save(commit=False)
                user_info.user = user

                if 'profile_pic' in request.FILES:
                    user_info.profile_pic = request.FILES['profile_pic']
                user_info.save()
                registered = True
        else:
            user_form = UserForm()
            user_info_form = UserInfoForm()
        dict = {'user_form':user_form, 'user_info_form':user_info_form, 'registered':registered}
        return render(request, 'Login_app/register.html', context=dict)

My_Third_Project/templates/Login_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

  <title>{{ title }}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Login_app:index' %}">Home</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Login_app:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Login_app:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Login_app:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
    </div>
  </nav>
  <br>
  <div class="container">
    {% block body_block %}

    {% endblock %}
  </div>
</body>
</html>

My_Third_Project/templates/Login_app/index.html
<!DOCTYPE html>
{% extends 'Login_app/base.html' %}
{% block body_block %}
{% if user.is_authenticated %}
<p> hi {{ user_basic_info.username }}, </p>
<p>Your Email:  {{ user_basic_info.email }}</p>
<p> <a href="{{ user_more_info.facebook_id }}">Facebook Profile</a>
<img src="/media/{{ user_more_info.profile_pic }}" alt="" width="200px">
{% else %}
<div class="alert alert-warning">
  You are not logged in!
</div>
{% endif %}
{% endblock %}

My_Third_Project/templates/Login_app/login.html
{% extends 'Login_app/base.html' %}
{%block body_block %}
<h3>Please Login: </h3>
<form  action="{% url 'Login_app:user_login' %}" method="post">
  <label for="username">Username: </label>
  <input type="text" name="username" placeholder="Enter Username.." class="form-control" required>
  <label for="password">Password: </label>
  <input type="password" name="password" placeholder="Enter Password.." class="form-control" required>
  {% csrf_token %}
  <br>
  <input type="submit" name="submit" value="Login">
</form>
{% endblock %}

My_Third_Project/templates/Login_app/register.html
{% extends 'Login_app/base.html' %}
{% load static %}
{% block body_block %}
{% if registered %}
<div class="alert alert-success"> Congratulations! Registration Successful!!</div>
{% else %}
<form action="" enctype="multipart/form-data" method="post">
  {{ user_form.as_p }}
  {{ user_info_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Register">
</form>
{% endif %}
{% endblock %}